import { getIntegrationStatus } from "@/lib/integrations/status";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AdminMobileMoneyConfirm } from "@/components/admin/admin-mobile-money-confirm";
import { AdminIntegrationTests } from "@/components/admin/admin-integration-tests";

export const metadata = { title: "Integrations" };

export default function AdminIntegrationsPage() {
  const status = getIntegrationStatus();

  const items = [
    {
      name: "Twilio SMS",
      key: "sms",
      desc: "Order, delivery, and payment texts to customers & sellers (+231 supported).",
      setup: "npm run setup:integrations — then add Twilio keys to .env",
    },
    {
      name: "Web Push (VAPID)",
      key: "webPush",
      desc: "Browser notifications for logged-in customers.",
      setup: "Keys auto-generated by setup:integrations",
    },
    {
      name: "Flutterwave",
      key: "mobileMoney",
      desc: "Orange Money & MTN via one checkout link (optional; manual confirm without keys).",
      setup: "FLUTTERWAVE_SECRET_KEY + NEXT_PUBLIC_FLUTTERWAVE_PUBLIC_KEY",
    },
    {
      name: "SMTP Email",
      key: "email",
      desc: "Order confirmations and password reset.",
      setup: "SMTP_HOST, SMTP_USER, SMTP_PASS",
    },
  ];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Integrations</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Recommended stack for Markay Hall: Twilio + Web Push + Flutterwave (optional).
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {items.map((item) => {
          const s = status[item.key];
          return (
            <Card key={item.key}>
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between gap-2">
                  <CardTitle className="text-base">{item.name}</CardTitle>
                  <Badge variant={s.configured ? "secondary" : "outline"}>
                    {s.configured ? "Active" : "Not configured"}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-2 text-sm text-muted-foreground">
                <p>{item.desc}</p>
                <p className="text-xs">
                  <span className="font-medium text-foreground">Setup: </span>
                  {item.setup}
                </p>
                <p className="font-mono text-[10px]">{s.env.join(", ")}</p>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <AdminIntegrationTests />
        {!status.mobileMoney.configured ? (
          <div>
            <h2 className="mb-2 text-base font-semibold">Manual mobile money</h2>
            <AdminMobileMoneyConfirm />
          </div>
        ) : (
          <div className="rounded-lg border p-4 text-sm text-muted-foreground">
            <p className="font-medium text-foreground">Flutterwave active</p>
            <p className="mt-1">Mobile money checkout uses Flutterwave payment links. Configure webhooks in your Flutterwave dashboard.</p>
          </div>
        )}
      </div>
    </div>
  );
}
